name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  even_chapters:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/pyro-ppl/numpyro/archive/master.zip
        pip install -r requirements.txt 
        pip install nbval
    - name: Test with nbval
      run: |
        find notebooks -maxdepth 1 -name "[01][02468]*.ipynb" | sort -n | xargs pytest -vx --nbval-lax --durations=0


  odd_chapters:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/pyro-ppl/numpyro/archive/master.zip
        pip install -r requirements.txt
        pip install nbval
    - name: Test with nbval
      run: |
        find notebooks -maxdepth 1 -name "[01][13579]*.ipynb" | sort -n | xargs pytest -vx --nbval-lax --durations=0

